repos:
  - repo: https://github.com/get-woke/woke
    rev: v0.19.0
    hooks:
      - id: woke
        args: ["-c", "https://github.com/canonical-web-and-design/Inclusive-naming/raw/main/config.yml"]
        files: \.rst
